base_link: 'base_link'

# =====================================================
left_hand:
    end_effector_name: 'left_hand'  #ee group name

    #actuated joints in end effector
    joints : ['LHand']

    #open position
    #pregrasp_posture : [1.0] #for the real robot
    pregrasp_posture : [0.0] #for sim
    pregrasp_time_from_start : 4.0

    #close position
    #grasp_posture : [0.0] #for the real robot
    grasp_posture : [1.0] #for sim
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    #desired pose from end effector to grasp - [r, p, y] #1.5707 = PI/2
    #side grasp -pi/3 - best
    grasp_pose_to_eef : [0.0, 0.036, -0.03]
    grasp_pose_to_eef_rotation : [-1.5, 0.0, 0.0]

    end_effector_parent_link: 'l_grasp_link'

# =====================================================
right_hand:
    end_effector_name: 'right_hand'  #ee group name

    #actuated joints in end effector
    joints : ['RHand']

    #open position
    #pregrasp_posture : [1.0] #for the real robot
    pregrasp_posture : [0.0] #for sim
    pregrasp_time_from_start : 4.0

    #close position
    #grasp_posture : [0.0] #for the real robot
    grasp_posture : [1.0] #for sim
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    #desired pose from end effector to grasp - [r, p, y]
    #top grasp 40 deg - best
    grasp_pose_to_eef : [0.01, 0.0, 0.05] #0.145]
    grasp_pose_to_eef_rotation : [0, 0.6, 0]

    end_effector_parent_link: 'r_grasp_link'
